### ISSUE TITLE
Create scrollbar to improve on the default one

### ISSUE THREAD

**Issue by nyandika** [SpaceyaTech/Team-Rio-React#18]
The idea is not to replace the default browser scrollbar but rather to improve its experience

**Comment by AnthonyHad** [comment]
@nyandika I am open to taking on this challenge! 
I have been ramping on my React for a while and would love to put this all to practice.

In the case where I am assigned, what do you mean exactly by improving the experience?

**Comment by nyandika** [comment]
Um sort of like have it blend with the website. right now it's like a grey on white background bar. If we could have it like what is here in github that would be swell. or even disappear and show up in scroll mode. Just play around with it

**Comment by AnthonyHad** [comment]
@nyandika Sounds good, taking a look

**Comment by AnthonyHad** [comment]
Hey @nyandika 
I've understood what you meant and went ahead and read a lot on scrollbars. Tried to use packages and CSS to make modifications and suddenly it looked cleaner that how it was.  (cf image below)
I am not sure what caused this but can walk you through code which I added and then omitted

<img width="1440" alt="Screenshot 2022-11-12 at 00 40 16" src="https://user-images.githubusercontent.com/57102201/201444992-f5e3f798-4a10-4b59-86fd-9fb76d63f159.png">

**Comment by nyandika** [comment]
Yea that looks good
